#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/book?useSSL=false
#    username: root
#    password: Apple321!
#    # Hikari 数据源专用配置
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 5
#  # JPA 相关配置
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: false
#    hibernate:
#      ddl-auto: update
server:
  port: 8080
  servlet:
    context-path: /
  ssl:
    enabled: true
    # keystore 文件
    key-store: classpath:ssl/aarstore.com.keystore
    key-store-type: PKCS12
    # keystore的密码
    key-store-password: Apple321!
